export enum Errors {

    NOT_FOUND = 'NOT_FOUND',
    FORBIDDEN = 'FORBIDDEN',
    INVALID_VALUE = 'INVALID_VALUE',
    REQUEST_VALIDATION_ERROR = 'REQUEST_VALIDATION_ERROR',
    UNEXPECTED = 'UNEXPECTED_ERROR'

}
